<?php

$locale = array(
	// admin's menu
	'title'=>'тест вербальных ассоциаций университет Новосибирск - Париж 3 Новая Сорбонна',
	'keys'=>'Ключи',
	'dict'=>'Словари',
	'tests'=>'Тесты',
	'used'=>'Использованные ключи',
	'unused'=>'Свободные ключи',
	'lists'=>'Списоки',
	'tlist'=>'Список тестов',
	'tnew'=>'Новый тест',
	'right'=>'Прямой словарь',
	'back'=>'Обратный словарь',
	// unused_keys
	//'key'=>'',
	'key_lang'=>'Язык теста',
	't_lang'=>'Язык теста',
	'n_keys'=>'Количество ключей',
	'key_create'=>'Создать ключи',
	// used keys
	'keys_delete'=>'Удалить использованые ключи',
	// test list
	'cre_date'=>'Дата создания',
	'test_lang'=>'Язык теста',
	'test_create'=>'Создать тест',
	'descr'=>'Описание',
	// dict_right/back
	'stimul'=>'Стимул',
	'resp'=>'Отклик',
	'test'=> 'Тест',
	// other
	'cities'=>"Города",
	'age_failed' => 'Возраст задан не верно',
	'key' => 'Ключ',
	'login' => 'Вход',
	'ch_lang' => 'Выберете язык интерфейса',
	'ru' => 'Русский',
	'fr' => 'Француский',
	'en' => 'Английский',
	'de' => 'German',
	'it' => 'Italian',
	'es' => 'Spanish',
	'pg' => 'Portuguese',
	'bl' => 'Bulgarian',
	'rm' => 'Romanian',
	'cz' => 'Czech',
	'pl' => 'Polish',
	'bo' => 'Bosnian',
	've' => 'Hungarian',
	'gl' => 'Dutch',
	'gr' => 'Greek',
	'la' => 'Latvian',
	'lt' => 'Lithuanian',
	'mk' => 'Macedonian',
	'nd' => 'Netherlands',
	'dt' => 'Danish',
	'sz' => 'Swedish',
	'no' => 'Norwegian',
	'is' => 'Icelandic',
	'fi' => 'Finnish',
	'sb' => 'Serbian',
	'sc' => 'Slovak',
	'sl' => 'Slovene',
	'hv' => 'Croatian',
	'et' => 'Estonian',
	'ar' => 'Arabic',
	'vt' => 'Vietnamese',
	'oo' => 'Other',
	'db_error' => 'Ошибка подсоединения к базе данных',
	'key_invalide' => 'Неверный ключ',
	'unknown_error' => 'Неизвестная ошибка',
	'anketa_title' => 'Заполните, пожалуйста, анкету',
	'edu' => 'Образование',
	'edu_1'=>'Старшеклассинк',
	'edu_2'=>'Студент',
	'edu_3'=>'Аспирант',
	'edu_4'=>'Кандидат',
	'edu_5'=>'Доктор',
	'specs'=>'Специализации',
	'spec'=>'Специализация',
	'sex' => 'Пол',
	'sex_m' => 'Мужской',
	'sex_f' => 'Женский',
	'city' => 'Город где вы учитесь (работаете)',
	'donotcare'=>'Не важно',
	'from'=>'от',
	'adv_search'=>'Расширенный поиск',
	'to'=>'до',
	'age' => 'Возраст',
	'lang' => 'Родной язык',
	'Submit' => 'Сохранить',
	'search' => 'Поиск',
	'age_failed' => 'Неверный формат даты рождения',
	'age_empty' => 'Не задана дата рождения',
	'spec_failed' => 'Не указана специализация',
	'city_failed' => 'Не указан город',
	'empty' => 'Пустой ответ не допустим',
	'go' => 'Вперед!',
	'next' => 'Следующее',
	'word_left' => 'Осталось слов: ',
	'time_left' => 'Осталось времени на тест [сек]',
	'again' => 'Начать с начала',
	'thank_you' => 'Спасибо Вам за то, что приняли участие в тестировании',
	'test_descr' => 'Цель теста - составить словарь ассоциаций. Для этого Вам 
		предлагается список из 100 слов. На каждое слово надо ввести слово, с  
		которым оно ассоциируется для Вас, например &quot;кошка&quot; --&gt; 
		&quot;мыш&quot; или &quot;мурлыкать&quot; или &quot;черная&quot;. 
		На весь тест Вам отводится 15 минут. После того как ассоциация введена, 
		требуется нажать или клавишу &quot;Ввод&quot;, или щелкнуть указателем 
		мыши по кнопке &quot;Следующее&quot;. Если готовы, то жмите &quot;Вперед"&quot;.',
	
	'sp1'=>'экономика',
	'sp2'=>'биология',
	'sp3'=>'langues étrangères et traduction',
	'sp4'=>'информатика',
	'sp5'=>'physique, mécanique, électronique',
	'sp6'=>'lettres et littérature',
	'sp7'=>'sciences de l\'ingénieur',
	'sp8'=>'математика',
	'sp9'=>'право',
	'sp10'=>'médecine et métiers de la santé',
	'sp11'=>'науки о земле',
	'sp12'=>'chimie',
	'sp13'=>'orthophonie',
	'sp14'=>'sciences humaines',
	'sp15'=>'психология',
	'sp16'=>'pluridisciplinaire scientifique',
	'sp17'=>'история, архиология',
	'sp18'=>'arts et musicologie',
	'sp19'=>'communication - journalisme',
	'sp20'=>'agriculture - agronomie',
	'sp21'=>'horticulture - paysage',
	'sp22'=>'sciences du langage et cognitives',
	'sp23'=>'ressources humaines et carrières sociales',
	'sp24'=>'alimentaire et agroalimentaire',
	'sp35'=>'français langue étrangère',
	'sp36'=>'sciences sociales et politiques',
	'sp37'=>'architecture - urbanisme',
	'sp38'=>'technologies de l\'information',
	'sp39'=>'énergétique - électricité',
	'sp40'=>'sciences de l\'éducation',
	'sp41'=>'sciences des matériaux',
	'sp42'=>'télécommunications - réseaux',
	'sp43'=>'aucune',
	'sp44'=>'arts du spectacle',
	'sp45'=>'hôtellerie - tourisme',
	'sp46'=>'aéronautique',
	'sp47'=>'documentation',
	'sp48'=>'métiers du sport',
	'sp49'=>'autre',
	'sp50'=>'secrétariat',
	'region'=>'Область',
    'reg1'=>'Alsace',
    'reg2'=>'Aquitaine',
    'reg3'=>'Auvergne',
    'reg4'=>'Bourgogne ',
    'reg5'=>'Bretagne ',
    'reg6'=>'Centre',
    'reg7'=>'Champagne-Ardenne',
    'reg8'=>'Corse',
    'reg9'=>'Franche-Comté',
    'reg10'=>'Ile-de-France',
    'reg11'=>'Paris',
    'reg12'=>'Languedoc-Roussillon',
    'reg13'=>'Limousin',
    'reg14'=>'Lorraine',
    'reg15'=>'Midi-Pyrénées',
    'reg16'=>'Nord-Pas-de-Calais',
    'reg17'=>'Basse-Normandie',
    'reg18'=>'Haute-Normandie',
    'reg19'=>'Pays de la Loire',
    'reg20'=>'Picardie',
    'reg21'=>'Poitou-Charentes',
    'reg22'=>'Provence-Côte d\'Azur',
    'reg23'=>'Rhône-Alpes',
    'reg24'=>'Guyane',
    'reg25'=>'Guadeloupe ',
    'reg26'=>'Martinique ',
    'reg27'=>'Réunion',
    'reg28'=>'Belgique',
    'reg29'=>'Suisse',
    'reg30'=>'Canada',
	'reg-1'=>'Не Франция',

);

?>
