<?php

// for bilinguals Ru - Fr

$locale = array(
	// admin's menu
	'title'=>'Université de Novossibirsk <br>Test d’associations évoquées par les mots',
	'keys'=>'Keys',
	'dict'=>'Dictionaries',
	'tests'=>'Tests',
	'used'=>'Used keys',
	'unused'=>'Unused keys',
	'lists'=>'Lists',
	'tlist'=>'Tests list',
	'tnew'=>'Create test',
	'right'=>'Direct dictionary',
	'back'=>'Inverse dictionary',
	// unused_keys
	//'key'=>'',
	'key_lang'=>'Language of test',
	't_lang'=>'Language of test',
	'n_keys'=>'Number of keys',
	'key_create'=>'Create key(s)',
	// used keys
	'keys_delete'=>'Delete used keys',
	// test list
	'cre_date'=>'Date of creation',
	'test_lang'=>'Language of test',
	'test_create'=>'Create test',
	'descr'=>'Description',
	// dict_right/back
	'stimul'=>'Stimulus',
	'resp'=>'Response',
	'test'=> 'Test',
	// other
	'cities' => 'Cities',
	'age_failed' => 'Age is incorrect',
	'lang_failed' => 'Specify your natine language',
	'key' => 'Key',
	'login' => 'Enter',
	'ch_lang' => 'Choose language for interface',
	'ru' => 'Russian',
	'fr' => 'French',
	'en' => 'English',
	'de' => 'German',
	'it' => 'Italian',
	'es' => 'Spanish',
	'pg' => 'Portuguese',
	'bl' => 'Bulgarian',
	'rm' => 'Romanian',
	'cz' => 'Czech',
	'pl' => 'Polish',
	'bo' => 'Bosnian',
	've' => 'Hungarian',
	'gl' => 'Dutch',
	'gr' => 'Greek',
	'la' => 'Latvian',
	'lt' => 'Lithuanian',
	'mk' => 'Macedonian',
	'nd' => 'Netherlands',
	'dt' => 'Danish',
	'sz' => 'Swedish',
	'no' => 'Norwegian',
	'is' => 'Icelandic',
	'fi' => 'Finnish',
	'sb' => 'Serbian',
	'sc' => 'Slovak',
	'sl' => 'Slovene',
	'hv' => 'Croatian',
	'et' => 'Estonian',
	'ar' => 'Arabic',
	'vt' => 'Vietnamese',
	'oo' => 'Autre',
	'db_error' => 'Database connection error',
	'key_invalide' => 'The key is invalide',
	'test_invalide' => 'There is no an apropriate test',
	'unknown_error' => 'Unknown error',
	'anketa_title' => 'Remplissez le formulaire s\'il vous plaît',
	'edu' => 'Education',
	'edu_1'=>'Lycéen',
	'edu_2'=>'Étudiant',
	'edu_3'=>'Doctorant',
	'edu_4'=>'Docteur en sciences',
	'edu_5'=>'HDR',
	'edu_5'=>'Autre',
	'specs'=>'Domaine de spécialisation',
	'spec'=>'Domaine de spécialisation',
	'sex' => 'Sexe',
	'sex_m' => 'Homme',
	'sex_f' => 'Femme',
	'city' => 'Ville où vous passez ce test',
	'donotcare'=>'Do not care',
	'from'=>'from',
	'adv_search'=>'Advanced filter',
	'to'=>'To',
	'age' => 'Âge',
	'lang' => 'Langue maternelle',
	'Submit' => 'Save',
	'search' => 'Search',
	'age_failed' => 'birthday is invalide',
	'age_empty' => 'Age is required',
	'spec_failed' => 'Specialization is required',
	'city_failed' => 'City is required',
	'empty' => 'Empty',
	'go' => 'Aller!',
	'next' => 'Suivant',
	'word_left' => 'Mots restants: ',
	'time_left' => 'Temps restant [sec]',
	'again' => 'Start again',
	'thank_you' => 'Thank you for taking part in the test',
	'test_descr' => 'Vous allez voir apparaitre 50 mots différents. Nous vous prions de
bien vouloir inscrire le premier mot (ou expression) qui vous vient à
l’esprit en réaction à ce mot. Une fois le test terminé, vous pouvez le 
recommencer – les mots seront différents à chaque fois!
Nous vous prions également de le faire connaitre autour de vous parmi
des étudiants francophones.<br><br> Merci!',
	
	'sp1'=>'sciences économiques',
	'sp2'=>'biologie',
	'sp3'=>'langues étrangères et traduction',
	'sp4'=>'informatique',
	'sp5'=>'physique, mécanique, électronique',
	'sp6'=>'lettres et littérature',
	'sp7'=>'sciences de l\'ingénieur',
	'sp8'=>'mathématiques',
	'sp9'=>'droit',
	'sp10'=>'médecine et métiers de la santé',
	'sp11'=>'sciences de la terre',
	'sp12'=>'chimie',
	'sp13'=>'orthophonie',
	'sp14'=>'sciences humaines',
	'sp15'=>'psychologie',
	'sp16'=>'pluridisciplinaire scientifique',
	'sp17'=>'histoire - archéologie',
	'sp18'=>'arts et musicologie',
	'sp19'=>'communication - journalisme',
	'sp20'=>'agriculture - agronomie',
	'sp21'=>'horticulture - paysage',
	'sp22'=>'sciences du langage et cognitives',
	'sp23'=>'ressources humaines et carrières sociales',
	'sp24'=>'alimentaire et agroalimentaire',
	'sp35'=>'français langue étrangère',
	'sp36'=>'sciences sociales et politiques',
	'sp37'=>'architecture - urbanisme',
	'sp38'=>'technologies de l\'information',
	'sp39'=>'énergétique - électricité',
	'sp40'=>'sciences de l\'éducation',
	'sp41'=>'sciences des matériaux',
	'sp42'=>'télécommunications - réseaux',
	'sp43'=>'aucune',
	'sp44'=>'arts du spectacle',
	'sp45'=>'hôtellerie - tourisme',
	'sp46'=>'aéronautique',
	'sp47'=>'documentation',
	'sp48'=>'métiers du sport',
	'sp49'=>'autre',
	'sp50'=>'secrétariat',
	'region'=>'Pays',
	'reg1'=>'Alsace',
	'reg2'=>'Aquitaine',
	'reg3'=>'Auvergne',
	'reg4'=>'Bourgogne ',
	'reg5'=>'Bretagne ',
	'reg6'=>'Centre',
	'reg7'=>'Champagne-Ardenne',
	'reg8'=>'Corse',
	'reg9'=>'Franche-Comté',
	'reg10'=>'Ile-de-France',
	'reg11'=>'Paris',
	'reg12'=>'Languedoc-Roussillon',
	'reg13'=>'Limousin',
	'reg14'=>'Lorraine',
	'reg15'=>'Midi-Pyrénées',
	'reg16'=>'Nord-Pas-de-Calais',
	'reg17'=>'Basse-Normandie',
	'reg18'=>'Haute-Normandie',
	'reg19'=>'Pays de la Loire',
	'reg20'=>'Picardie',
	'reg21'=>'Poitou-Charentes',
	'reg22'=>'Provence-Côte d\'Azur',
	'reg23'=>'Rhône-Alpes',
	'reg24'=>'Guyane',
	'reg25'=>'Guadeloupe ',
	'reg26'=>'Martinique ',
	'reg27'=>'Réunion',
	'reg28'=>'Belgique',
	'reg29'=>'Suisse',
	'reg30'=>'Canada',
	'reg-1'=>'Not France',
);

?>
